# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Core CI

on:
  push:
     branches: [ "main", "dev" ]
  pull_request:
     branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore NuGet packages for API
      run: dotnet restore api/MatchSpark.API/MatchSpark.API.csproj
    - name: Restore NuGet packages for API Tests
      run: dotnet restore api/MatchSpark.API.Tests/MatchSpark.API.Tests.csproj
    - name: Build with dotnet
      run: dotnet build api/MatchSpark.API/MatchSpark.API.csproj --configuration Release
    - name: Test with dotnet
      run: dotnet test api/MatchSpark.API.Tests/MatchSpark.API.Tests.csproj --no-restore
